apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: react-app-be
  
resources:
- ../../base
- envs



patches:
- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: react-app-backend
    version: v1
- path: ./patches/service-patch.yaml
  target:
    kind: Service
    name: react-app
    version: v1


images:
- name: yasminemarzouk/app-react-be
  newTag: latest123
