apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-list-fe

resources:
- ../../base


patches:
- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    version: v1
- path: ./patches/service-patch.yaml
  target:
    kind: Service
    name: todo-list-frontend
    version: v1


    

images:
- name: faysalmehedi/rl-frontend
  newTag: v2