apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization 


configMapGenerator:
  - envs:
      - config.env 
    name: env-configs
    namespace: minio

  
secretGenerator:
 - name: env-secrets
   envs:
     - secrets.env
   namespace: minio



generatorOptions:
 disableNameSuffixHash: true
