
- op: add
  path: /spec/template/spec/containers/0/resources
  value:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"

- op: replace
  path: /spec/template/spec/containers/0/image
  value: prom/prometheus 
  
- op: add
  path: /spec/template/spec/containers/0/args
  value:
    - "--storage.tsdb.retention.time=12h"
    - "--config.file=/etc/prometheus/prometheus.yml"
    - "--storage.tsdb.path=/prometheus/"

- op: replace
  path: /spec/template/spec/volumes
  value:
    - name: prometheus-config-volume
      configMap:
        defaultMode: 420
        name: prometheus-server-conf
    - name: prometheus-storage-volume
      emptyDir: {}

- op: replace
  path: /spec/template/spec/containers/0/volumeMounts
  value:
    - name: prometheus-config-volume
      mountPath: /etc/prometheus/
    - name: prometheus-storage-volume
      mountPath: /prometheus/
