apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
namespace: prometheus


resources:
- ../../base


patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: prometheus
    version: v1

- path: ./patches/service-patch.yaml
  target:
    kind: Service
    name: prometheus
    version: v1

 


