apiVersion: v1
kind: Service
metadata:  
  name: frontend
  labels:
    component: < component name >
spec: 
  type: NodePort
  ports: 
  - name: http
    port: 8079
    protocol: TCP
    targetPort: 8079
  selector:
    component: < component name >

    
