apiVersion: v1
kind: ConfigMap
metadata:
  name: shopping-init-scripts
  labels:
    app: mongodb-init

data:
  init.js: |
    db = db.getSiblingDB('react_db');
    db.createUser({
      user: 'react_user',
      pwd: 'react_user@123',
      roles: [
        { role: 'readWrite', db: 'react_db' },
        { role: 'dbAdmin', db: 'react_db' }
      ]
    });