apiVersion: v1
kind: Service
metadata:  
  name: backend
  labels:
    component: < component name >
spec: 
  type: NodePort
  ports: 
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    component: < component name >



    
