apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-sync-running.teams: ArgoCD
    notifications.argoproj.io/subscribe.on-deployed.teams: ArgoCD
    notifications.argoproj.io/subscribe.on-health-degraded: ArgoCD
  name: dev-advertice
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: advertise
    server: {{ .Values.spec.destination.server }}
  project: adevertising
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: adevertising/microservices/advertice/kustomize/overlays/dev
    targetRevision: {{ .Values.spec.source.targetRevision }}
