apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization 


configMapGenerator:
  - envs:
      - config.env 
    name: env-configs
    namespace: shopping-be

  
secretGenerator:

 - name: env-secrets
   envs:
     - secrets.env
   namespace: shopping-be



generatorOptions:
 disableNameSuffixHash: true
