apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-backend
  labels:
    app: react-app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app-backend
  template:  
    metadata:
      labels:
        app: react-app-backend
    spec:
      containers:
      - name: react-app-backend
        image:  < REGISTRY / IMAGE >
        ports:
          - containerPort: 4000
        imagePullPolicy: Always

