apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
    - namespace.yaml
    - service.yaml
    - deployment.yaml
    - mongodb-cm.yaml

   

generatorOptions:
 disableNameSuffixHash: true
