apiVersion: v1
kind: Service
metadata:  
  name: react-app
  labels:
    component: < component name >
spec: 
  type: NodePort
  ports: 
  - name: http
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    component: < component name >



    
