apiVersion: v1
kind: Service
metadata:  
  name: kibana
  labels:
    component: < component name >
spec: 
  type: NodePort
  ports: 
  - name: http
    port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    component: < component name >


    
