
- op: replace
  path: /spec/template/spec/containers/0/image
  value: "weaveworksdemos/carts"

- op: add 
  path: /spec/revisionHistoryLimit
  value: 2  

- op: add
  path: /spec/template/spec/containers/0/resources
  value:
    requests:
      cpu: "200m"
      memory: "180Mi"
    limits:
      cpu: "300m"
      memory: "350Mi"
