apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
    - service.yaml
    - deployment.yaml
    - prometheus.yml
    - namespace.yaml
    - grafana-pvc.yml
    - grafana-rbac.yaml
    - grafanaconfigmap.yaml
    
    
   

generatorOptions:
 disableNameSuffixHash: true
