apiVersion: v1
kind: Service
metadata:  
  name: grafana
  labels:
    component: < component name >
spec: 
  type: NodePort
  ports: 
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    component: < component name >


    
