apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: < REGISTRY / IMAGE >
          ports:
            - containerPort: 9000
            - containerPort: 9001
          imagePullPolicy: Always
          volumeMounts:
            - name: minio-storage
              mountPath: "/data"
      volumes:
        - name: < volume name>
          persistentVolumeClaim:
            claimName: < claim name >