apiVersion: v1
kind: Service
metadata:  
  name: minio
  labels:
    component: < component name >
spec: 
  type: ClusterIP
  ports: 
  - name: http
    port: 9000
    targetPort: 9000
  - name: console
    port: 9001
    targetPort: 9001
  selector:
    component: < component name >


    
