apiVersion: v1
kind: Service
metadata:  
  name: elasticsearch
  labels:
    component: < component name >
spec: 
  type: NodePort
  ports: 
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    component: < component name >


    
