apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
    - service.yaml
    - deployment.yaml
    - prometheus-configmap.yaml
    - namespace.yaml
    - prometheus-rbac.yaml
    
   

generatorOptions:
 disableNameSuffixHash: true
