apiVersion: v1
kind: Service
metadata:  
  name: prometheus
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
  labels:
    component: < component name >
spec: 
  type: NodePort
  ports: 
  - port: 9090      
    targetPort: 9090  
    nodePort: 30000
   
  selector:
    component: < component name >


    
