apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization 


configMapGenerator:
  - envs:
      - config.env 
    name: env-configs
    namespace: catalogue

  
secretGenerator:
 - name: mysql-secrets
   envs:
     - mysql.env
   namespace: catalogue
 - name: env-secrets
   envs:
     - secrets.env
   namespace: catalogue



generatorOptions:
 disableNameSuffixHash: true
