apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shopping-frontend
resources:
- ../../base


patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: frontend
    version: v1

- path: ./patches/service-patch.yaml
  target:
    kind: Service
    name: frontend
    version: v1

images:
- name: weaveworksdemos/front-end
  newTag: 0.3.12


