apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
namespace: grafana


resources:
- ../../base


patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: grafana
    version: v1

- path: ./patches/service-patch.yaml
  target:
    kind: Service
    name: grafana
    version: v1


- path: ./patches/resource-quota-patch.yaml
  target:
    kind: ResourceQuota
    name: grafana
    version: v1

images:
- name: grafana/grafana
  newTag: latest
