apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vote

resources:
- ../../base





patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    version: v1
- path: ./patches/service-patch.yaml
  target:
    kind: Service
    name: vote
    version: v1

    

