apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: postgresql
  name: todo-list-postgresql
spec:
  ports:
  - name: tcp-postgresql
    port: 5432
    protocol: TCP
    targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/name: postgresql
  type: ClusterIP
