apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb
  labels:
    app: postgres
data:
  init.sql: |
    CREATE DATABASE books ;
    CREATE USER postgres WITH PASSWORD 'postgres' ;
    GRANT ALL PRIVILEGES ON DATABASE books TO books ;
    GRANT CREATE ON SCHEMA public TO books;
    ALTER USER postgres WITH SUPERUSER;
    CREATE DATABASE user;
    CREATE USER user WITH PASSWORD 'postgres';
    GRANT ALL PRIVILEGES ON DATABASE user TO user ;
    GRANT CREATE ON SCHEMA public TO user;
    ALTER USER user WITH SUPERUSER;

