apiVersion: v1
kind: Service
metadata:  
  name: todo-list-backend
  labels:
    component: < component name >
spec: 
  type: NodePort
  ports: 
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    component: < component name >


    
