apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: card

resources:
- ../../base


patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    version: v1
    name: card
- path: ./patches/service-patch.yaml
  target:
    kind: Service
    name: card
    version: v1

    
images:
- name: weaveworksdemos/carts
  newTag: 0.4.8

