
- op: replace
  path: /spec/template/spec/containers/0/image
  value: "faysalmehedi/rl-frontend"

- op: add
  path: /spec/template/spec/containers/0/env
  value:
    - name: API_HOST
      value: "10.244.1.3"
- op: add 
  path: /spec/revisionHistoryLimit
  value: 2  

- op: add
  path: /spec/template/spec/containers/0/resources
  value:
    requests:
      cpu: "8m"
      memory: "225Mi"
    limits:
      cpu: "16m"
      memory: "450Mi"
