apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio
  
resources:
- ../../base
- envs

patches:
- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: minio
    version: v1
    
- path: ./patches/service-patch.yaml
  target:
    kind: Service
    name: minio
    version: v1

- path: ./patches/resource-quota-patch.yaml
  target:
    kind: ResourceQuota
    name: doc-app-quota-be
    version: v1
    
images:
- name: docker.io/bitnami/minio
  newTag: "2022"
