
- op: replace
  path: /spec/template/spec/containers/0/image
  value: "weaveworksdemos/front-end"

- op: add 
  path: /spec/revisionHistoryLimit
  value: 2  

- op: add
  path: /spec/template/spec/containers/0/resources
  value:
    requests:
      cpu: "8m"
      memory: "225Mi"
    limits:
      cpu: "16m"
      memory: "450Mi"


