apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization 


configMapGenerator:
- envs:
  - config.env 
  name: env-configs
  namespace: todo-list-be

secretGenerator:
  - name: postgresql
    envs:
      - postgress.env
    namespace: todo-list-be 
  - name: env-secrets
    envs:
     - secrets.env


generatorOptions:
  disableNameSuffixHash: true
