apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    app: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
  template:  
    metadata:
      labels:
        app: catalogue
    spec:
      containers:
      - name: catalogue
        image:  < REGISTRY / IMAGE >
        ports:
          - containerPort: 3000
        imagePullPolicy: Always

