apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: catalogue-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  serviceName: catalogue-mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: docker.io/bitnami/mysql:8.0.22-debian-10-r23
        ports:
         - containerPort: 3306
        volumeMounts:
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-initdb
        configMap:
          name: mysql-configmap