apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  init.sql: |-
    SET GLOBAL event_scheduler = ON;
    CREATE DATABASE IF NOT EXISTS `catalogue` 
    CHARACTER SET utf8mb4   
    COLLATE utf8mb4_unicode_ci;
    CREATE USER IF NOT EXISTS 'catalogue'@'%' IDENTIFIED BY 'rootpassword';
    GRANT ALL PRIVILEGES ON catalogue.* TO 'catalogue'@'%';
    FLUSH PRIVILEGES;
    use catalogue;

