apiVersion: apps/v1
kind: Deployment
metadata:
  name: card
  labels:
    app: card
spec:
  replicas: 1
  selector:
    matchLabels:
      app: advertice
  template:
    metadata:
      labels:
        app: advertice
    spec:
      serviceAccountName: card
      containers:
      - name: server
        image: < REGISTRY / IMAGE >
        env:
         - name: JAVA_OPTS
           value: -Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
        ports:
        - containerPort: 9555
        
       
