apiVersion: apps/v1
kind: Deployment
metadata:
  name: card
  labels:
    app: card
spec:
  replicas: 1
  selector:
    matchLabels:
      app: card
  template:
    metadata:
      labels:
        app: card
    spec:
      serviceAccountName: card
      containers:
      - name: carts
        image: <REGISTRY/IMAGE>
        ports:
        - containerPort: 9555