apiVersion: v1
kind: Service
metadata:  
  name: card
  labels:
    component: < component name >
spec: 
  type: NodePort
  ports: 
  - name: http
    port: 10001
    protocol: TCP
    targetPort: 10001
  selector:
    component: < component name >

    
