apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
namespace: kibana


resources:
- ../../base


patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: kibana
    version: v1

- path: ./patches/service-patch.yaml
  target:
    kind: Service
    name: kibana
    version: v1



images:
- name: docker.elastic.co/kibana/kibana
  newTag: 7.12.0
