apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
namespace: todo-list-be

resources:
- ../../base
- envs
  
patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: todo-list-backend
    version: v1
- path: ./patches/service-patch.yaml
  target:
    kind: Service
    name: todo-list-backend
    version: v1
- path: ./patches/postgresql-deploy-patch.yaml
  target:
    kind: StatefulSet
    name: todo-list-postgresql
    version: v1
- path: ./patches/postgresql-service-patch.yaml
  target:
    kind: Service
    name: todo-list-postgresql
    version: v1

images:
- name: faysalmehedi/rl-backend
  newTag: v1
