apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-sync-running.teams: ArgoCD
    notifications.argoproj.io/subscribe.on-deployed.teams: ArgoCD
    notifications.argoproj.io/subscribe.on-health-degraded: ArgoCD
  name: shopping-fe
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: shopping-frontend
    server: {{ .Values.spec.destination.server }}
  project: shopping
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: online-shopping/microservices/frontend/kustomize/overlays/dev
    targetRevision: {{ .Values.spec.source.targetRevision }}
