apiVersion: v1
kind: Service
metadata:  
  name: todo-list-frontend
  labels:
    component: < component name >
spec: 
  type: NodePort
  ports: 
  - name: http
    port: 30080
    protocol: TCP
    targetPort: 30080
  selector:
    component: < component name >